### ISSUE TITLE
Content of services page should probably be black?

### ISSUE THREAD

**Issue by tyesamson** [tyesamson/the-finishing-suite#13]
That or change out the bg photo instead?

**Comment by mattdwen** [comment]
![image](https://user-images.githubusercontent.com/452295/35899501-a81b75ea-0c31-11e8-8f0e-af0cf897ba69.png)

Yeah the shadow of the couch bites you with black. Which is a pity, it's a cool image.

Any other images?

**Comment by tyesamson** [comment]
does this look terrible? https://i.imgur.com/g7ufDbb.jpg

**Comment by tyesamson** [comment]
Will have to shoot something new otherwise

**Comment by mattdwen** [comment]
![image](https://user-images.githubusercontent.com/452295/35899749-0697ded2-0c33-11e8-9ce3-803c5f79e3e2.png)

I can lighten/darken it in the page. I've also made the text in the list bold which helps. This is with a 10% white overlay on the image.

**Comment by tyesamson** [comment]
sorry to be a fucking pain but can you try opposite? white text on a darkened version of image?

**Comment by mattdwen** [comment]
Was just doing that :)

![image](https://user-images.githubusercontent.com/452295/35899805-6a4c929c-0c33-11e8-9162-2e7135a00f7c.png)

Bold, white, on 30% darkened.

**Comment by tyesamson** [comment]
I reckon that's the go :)
