### ISSUE TITLE
somehow http:// and https:// display content in different fonts

### ISSUE THREAD

**Issue by tyesamson** [tyesamson/the-finishing-suite#38]

**Comment by tyesamson** [comment]
https:// should match http://

**Comment by mattdwen** [comment]
This will probably get fixed with #40, but I can force it all to use https for now which should solve it.

**Comment by tyesamson** [comment]
Https is wrong font (serif) http is correct font (sans)

How is it even possible??

**Comment by mattdwen** [comment]
When the page is served over https, the browsers block things from loading on http these days. I've changed the font urls to have https, and added to the facebook and imdb links as well.

**Comment by tyesamson** [comment]
✌️
