### ISSUE TITLE
facebook pixel and google analytics

### ISSUE THREAD

**Issue by tyesamson** [tyesamson/the-finishing-suite#39]
https://www.facebook.com/business/help/952192354843755

**Comment by mattdwen** [comment]
You'll need to do the setup and send me the code. There's a section in there for **Someone else makes changes to my website**.

**Comment by mattdwen** [comment]
Same for GA, you'll need to set up your account then it should just give you some code to copy and paste.

**Comment by tyesamson** [comment]
google analytics...

Global Site Tag (gtag.js)

This is the Global Site Tag (gtag.js) tracking code for this property. Copy
and paste this code as the first item into the <HEAD> of every webpage you
want to track. If you already have a Global Site Tag on your page, simply
add the *config* line from the snippet below to your existing Global Site
Tag.




<script async src="
https://www.googletagmanager.com/gtag/js?id=UA-113963695-1"></script>

<script>

  window.dataLayer = window.dataLayer || [];

  function gtag(){dataLayer.push(arguments);}

  gtag('js', new Date());


  gtag('config', 'UA-113963695-1');

</script>
