### ISSUE TITLE
is there any way to autodirect all http:// traffic to https:// ?

### ISSUE THREAD

**Issue by tyesamson** [tyesamson/the-finishing-suite#40]

**Comment by mattdwen** [comment]
It depends on the hosting platform, where do you have it?

**Comment by tyesamson** [comment]
Dreamhost

**Comment by mattdwen** [comment]
Apache or Nginx?

https://help.dreamhost.com/hc/en-us/articles/115003505112-How-to-force-your-site-to-redirect-to-https-SSL-

**Comment by tyesamson** [comment]
I've always just assumed Apache, let me poke around control panel

**Comment by tyesamson** [comment]
Can't see anywhere in panel. Is there a way to tell via ssh?

**Comment by mattdwen** [comment]
Depends where your root access is. If it's Apache there's probably an .htaccess file, or if Nginx it looks like there should be a nginx folder at root with the domain as a sub dir.

**Comment by mattdwen** [comment]
I'm happy to look if you want to send your login.

**Comment by tyesamson** [comment]
its apache but there is no htaccss file — is that weird?

**Comment by mattdwen** [comment]
I've added the .htaccess to the latest develop branch, we'll see what that does.
If it breaks the site, delete the file.

**Comment by tyesamson** [comment]
Works! But now the portfolio is broken and wont load — something in the portfolio using http link maybe?

**Comment by mattdwen** [comment]
My bad, jquery link. Fixed now, download that same zip again.
