### ISSUE TITLE
bakground images scroll with section, should be fixed

### ISSUE THREAD

**Issue by tyesamson** [tyesamson/the-finishing-suite#43]
compare jakethemovie.com with thefinishingsuite.co.nz

it looks a little fancier the way it is on the jake site, i reckon.

scrolling the text over the image rather than with the image also makes it easy for a user to move the word they're currently at over the image if it's hard to read — see line in about section over the highlight in the bg photo.

**Comment by tyesamson** [comment]
updated index.html attached as txt file

[index.txt](https://github.com/mattdwen/the-finishing-suite/files/1729759/index.txt)

**Comment by mattdwen** [comment]
I've updated it. Looks a little weird with about and services going straight into each other. 

https://github.com/mattdwen/the-finishing-suite/archive/develop.zip

**Comment by tyesamson** [comment]
Looks way better I reckon! It's a simple effect it but gives the whole site
another dimension. Thanks <3
