### ISSUE TITLE
[short-term] prompt to scroll

### ISSUE THREAD

**Issue by tyesamson** [tyesamson/the-finishing-suite#46]
honestly not sure if this is even necessary at all, but does their need to be a design element that prompts the user to scroll down for more content?

**Comment by mattdwen** [comment]
I don't think it's required. Everyone knows websites scroll, and if they don't, there's a menu there they're going to click which does it for you.

Your call though.

**Comment by tyesamson** [comment]
1000% i trust your gut on that one!
