### ISSUE TITLE
[short-term] is phone number encoded?

### ISSUE THREAD

**Issue by tyesamson** [tyesamson/the-finishing-suite#49]
i’m sure it probably is already just double checking

**Comment by mattdwen** [comment]
I'm not sure what you mean by this one?

**Comment by tyesamson** [comment]
maybe i dreamed this?

because my phone number is in the current code that's live!

but i could've sworn that when this site was originally built, i was told that there was a way to encode a phone number in a website in a way that made it not immediately visible in the source code and therefore harder to be scraped by scammers/spammers?

 i'm going to have a search

**Comment by tyesamson** [comment]
so it wasn't this website that i was pointed to originally, but this is the one that i can find now: https://ctrlq.org/encode/

so

&#43;&#54;&#52;&#50;&#49;&#51;&#54;&#57;&#53;&#52;&#52;

would be the equivalent for my phone number and 

&#97;&#108;&#97;&#115;&#116;&#97;&#105;&#114;&#64;&#116;&#104;&#101;&#102;&#105;&#110;&#105;&#115;&#104;&#105;&#110;&#103;&#115;&#117;&#105;&#116;&#101;&#46;&#99;&#111;&#46;&#110;&#122;

would be my email address

is this junk science?

**Comment by tyesamson** [comment]
oh wow, so githib auto replaced the strings i entered with my phone number and email address
