### ISSUE TITLE
Change existing picture slider to have both stills and embedded youtube links

### ISSUE THREAD

**Issue by mattdwen** [tyesamson/the-finishing-suite#5]

**Comment by tyesamson** [comment]
Is there any way for each slide to have its own unique caption below the slider (not over the image) where I can list what I did on each job? Because some stuff will for offline and some online/grading etc.

**Comment by tyesamson** [comment]
new slider images will all be 16x9 not 2.35 as the jake stuff is

**Comment by mattdwen** [comment]
Example for reference: 
![image](https://user-images.githubusercontent.com/452295/35960324-26ab597a-0d0e-11e8-9efc-90edbd7edb7e.png)

**Comment by mattdwen** [comment]
I've got this layout mostly working, except for the flipped image underneath. I can do that automatically, but it's not going to work with any videos.

If you want something for the videos, then you'll have to make a still manually for every slide and manually change the URL in the code for each slide.

Or just put a generic background under each.

**Comment by tyesamson** [comment]
I was actually thinking last night of not embedding YT videos in the slider
and instead having them all be stills and if you click the still then an
embedded yt video opens in popup? Is that easier or harder? Don't want to
make anything harder for you but if that makes shit cleaner and easier for
you then best way forward?
