### ISSUE TITLE
[short-term] some screen resolutions mess with how bg images are displayed

### ISSUE THREAD

**Issue by tyesamson** [tyesamson/the-finishing-suite#52]
this is an example of how photos appear on my ipad 
![600542FA-2CCF-4D63-A4B5-06298DEFCBBC](https://user-images.githubusercontent.com/36214370/163275297-851a62b7-6bc1-4e50-a4ec-cd08192dc3c9.png)

**Comment by mattdwen** [comment]
Semi-fixed. On iOS the trade-off is you can't have the background images "fixed" as the content scrolls, and make it properly cover the screen at the same time. Please address all complaints to support@apple.com.
