### ISSUE TITLE
[immediate-term] teach al how to access and edit gallery via cms so i can start focusing on populating that

### ISSUE THREAD

**Issue by tyesamson** [tyesamson/the-finishing-suite#53]

**Comment by mattdwen** [comment]
CMS, lol, are you familiar with notepad dot e x e?

**Comment by tyesamson** [comment]
I am 🤣

Sorry, for some reason I was under the impression that you had moved the old version, which was just html and css, into a CMS system, and that that was what the primary overhaul was — you rebuilding it in that CMS. Clearly I know way less than I think I do lol. Would be good to sit down and go through it forensically when you have the time to do that
