### ISSUE TITLE
Project view in gallery being full width means not seeing the credits are there or sometime even the bottom of the image

### ISSUE THREAD

**Issue by tyesamson** [tyesamson/the-finishing-suite#59]
I think we need to shrink the project view to not be full width so that if it's a 16/x9 image you at least get a hint that there are credits there.

obviously this will depend on browser window ratio, but even just maximixed on a 16x9 hui monitor means not seeing whole image and definitely not getting any indication of credits.

**Comment by mattdwen** [comment]
I've forced images to not be taller than 75% of the screen height, and scale accordingly.
Videos are also 75% high max, and 16:9 fixed ratio.

**Comment by tyesamson** [comment]
this looks amazing -- the last (seriously!) thing for teh gallery is that i think it needs to be anchored to the centre rather than the top of the browser? see https://i.imgur.com/CMwCdcW.jpg
