### ISSUE TITLE
would it be possible to remove ‘handover’ from the menu but for the link to still work?

### ISSUE THREAD

**Issue by tyesamson** [tyesamson/the-finishing-suite#70]
so no one can navigate to the doc directly but if i direct link them to https://www.thefinishingsuite.co.nz/handover then it still takes them to the doc?

**Comment by mattdwen** [comment]
You can remove it from the nav fine, but that URL won't work at the moment.

It again depends again on the web host, if it's Apache/nginx for example, you modify the .htaccess file to write redirect rules.

**Comment by tyesamson** [comment]
copy that! looking at the old site, that's exactly the case! i can move and edit the .htaccess myself :)

**Comment by mattdwen** [comment]
Send me a copy of .htaccess?

**Comment by tyesamson** [comment]
[htaccess.zip](https://github.com/tyesamson/the-finishing-suite/files/8666212/htaccess.zip)

had to remove . and change file ext to zip for it to upload so just rename to .htaccess
