### ISSUE TITLE
is it possible for http to auto redirect to https?

### ISSUE THREAD

**Issue by tyesamson** [tyesamson/the-finishing-suite#71]

**Comment by mattdwen** [comment]
It is, depends on your web hosting setup and what the web server is.

Other option is to put Cloudflare in front of the site, which gives you caching and handles all https as well.

**Comment by tyesamson** [comment]
hosting is dreamhost vps and i just use their built in let's encrypt feature

**Comment by tyesamson** [comment]
turns out this is just a feature i needed to turn on in my vps panel lol
